name = "VisualGeometryOptimization"
uuid = "69c13e0b-7fe7-492d-975b-4112821fd6ea"
authors = ["Oliver Woodford"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
